### ISSUE TITLE
Get an error pop up with "temporal" message after clicking on stop in Track Monitor Completion status function

### ISSUE THREAD

**Issue by GovindarajKarthik** [Equipment-and-Tool-Institute/iumpr#101]
In IUMPR Data Collection Tool v1.9.5, get an error pop up with "temporal" message as shown in the attached screen shot after clicking on stop in Track Monitor Completion status function.
![Temporal Error pop up](https://github.com/Equipment-and-Tool-Institute/iumpr/assets/40402282/1579ad56-1faf-4030-93ca-5cb07da4b75b)

Subsequently in the same IUMPR Data Collection Tool v1.9.5 , unable to reload the previously captured log file. Get an error message      "File cannot be used. There are no Monitored Systems in the file. Please select a different file." Screen shot with the error message is attached for your reference. 
![Reload File Error](https://github.com/Equipment-and-Tool-Institute/iumpr/assets/40402282/34c700ae-8062-46c6-b015-8462ec5610ae)

**Comment by battjt** [comment]
Can we get a larger part of the report, or preferably the entire report to karys@soliddesign.net ?

**Comment by ericthomasswenson** [comment]
@GovindarajKarthik will confirm this behavior for 1.9.7

**Comment by ericthomasswenson** [comment]
No repeat complaint on release 1.9.6 or 1.9.7.
