### ISSUE TITLE
VIN and DM19 Mismatch errors in version 1.9.7

### ISSUE THREAD

**Issue by anthonyhbest** [Equipment-and-Tool-Institute/iumpr#107]
When testing version 1.9.7 we encountered an error when progressing from "Generate Data Plate" to "Collect Test Results" where the tool will display one of the two errors below:
![4d2b2b41-fc80-4f7d-be48-f849f8ed72fd](https://github.com/Equipment-and-Tool-Institute/iumpr/assets/94923793/1616eca9-03b9-4103-acba-201f17613152)

![7fc641c7-8f97-49fe-924d-513e88f97745](https://github.com/Equipment-and-Tool-Institute/iumpr/assets/94923793/84cbe169-74ab-4c52-9479-7d4849b7c3a3)

I believe this is a result of DM19/VIN missing from the test log file.  I will send the raw CAN logs to @battjt  directly.
This looks like a reoccurrence of issue #88.

**Comment by ericthomasswenson** [comment]
Observed when exiting Function B … and starting C or other functions.

**Comment by ericthomasswenson** [comment]
Anthony… is this a consistent error or sporadic?

**Comment by anthonyhbest** [comment]
Consistent.  We were unable to get any test data to review.

**Comment by jacobbosch-cummins** [comment]
We were able to mostly replicate with 1.9.7.  The popup box with the CALIDs and CVNs was not observed, but the popup with the VIN error was observed.  The test log did not have DM19 data nor a VIN.

A much older version of the tool was also tried and the issue was not present.

**Comment by ericthomasswenson** [comment]
Jacob Bosch confirmed this performance in an ECM HIL.

**Comment by battjt** [comment]
Does anyone have a .asc file and the corresponding .iumpr report that I can use for tests?  I'm unable to reproduce this error with my bench.

**Comment by jacobbosch-cummins** [comment]
@battjt I have sent the logs to Joe via email.

**Comment by anthonyhbest** [comment]
The issue appears to be repaired in 1.9.8.

**Comment by ericthomasswenson** [comment]
Bob confirmed with a 9-Calid DM19

**Comment by ericthomasswenson** [comment]
Multiple reports of success.
