### ISSUE TITLE
Tables do not fit on printed page

### ISSUE THREAD

**Issue by gumbelmj** [Equipment-and-Tool-Institute/iumpr#15]
The DM20 and DM5 summary tables do not fit properly on a page when printed to PDF or paper.

**Comment by joekartje** [comment]
Horizontal Comparisons of Numerators and Denominators do not Fit on an 8/5x11 page. 
Ideally whatever we come up with needs to fit on one page.  Narrow (½ inch margins at the minimum).  ¾ inch much preferred to ½.

**Comment by gumbelmj** [comment]
Reduced the width of both the Monitor System and Performance Ratios tables.
