### ISSUE TITLE
DM24 Queries Timed out for V1

### ISSUE THREAD

**Issue by joekartje** [Equipment-and-Tool-Institute/iumpr#17]

**Comment by joekartje** [comment]
Eric to attempt to have this checked on a vehicle similar to V1 to see if the issue can be duplicated.

**Comment by joekartje** [comment]
In function D [Monitor Status Loop], DM24 was not received from SA 0 and only the SA 55 test results were collected.  There was no timeout error shown.

**Comment by joekartje** [comment]
Jamie Phillips confirmed the DM24 failure for N13 (two controller) engines in a back to back demonstration of the IUMPR and J1939-84 tools.  The IUMPR tool recorded a timeout for the engine’s DM24 response.  The -84 tool received the DM24 content Key On Engine Off (Part 1) and Key On Engine Running (Part 2). 
(See email "L1 and L2 tool tests on 745 Prostar [Similar to V1 at NPG DM24 issue]" dated 6/21/2017.

**Comment by gumbelmj** [comment]
Looking at V2-D1 it shows a timeout for the DM24 Request:

2017-06-06T11:16:56.730 Direct DM24 Request to Engine #1 (0)
2017-06-06T11:16:56.730 18EA00F9 B6 FD 00 (TX)
Error: Timeout - No Response.
2017-06-06T11:17:00.482 ERROR No tests results returned

Looking at the traffic logs there are only two "busy" responses from the engine:

2017-06-06 11:16:57.988 P->18E80000 03 FF FF FF F9 B6 FD 00
2017-06-06 11:16:59.236 P->18E80000 03 FF FF FF F9 B6 FD 00

Unfortunately, we don't echo our own traffic to know that we actually requested it three times.

**Comment by joekartje** [comment]
Eric has suggested a 2.5 second timeout for everything besides DM24 and a 5 second timeout for DM24.

**Comment by joekartje** [comment]
Eric and Kartje discussed this on July 3 and came up with the following suggestion:  2.5 second timeout for everything besides DM24 and a 10-15 second timeout for DM24.  The trade off is a longer timeout will result in slower application performance, but provide more headroom for future growth.

**Comment by gumbelmj** [comment]
Changed the default timeout to 2.5 seconds.  Updated the timeout for DM24 to 15 seconds.  The application will end the wait early if the response is received before that.  Also enabled Echoing on the adapter to allow the requests to be added to the debug log
