### ISSUE TITLE
DM20 Queries Timed out for V2

### ISSUE THREAD

**Issue by joekartje** [Equipment-and-Tool-Institute/iumpr#18]

**Comment by joekartje** [comment]
In Function C, DM20 queries timed out for V2.  They were received in Functions B and E.

**Comment by gumbelmj** [comment]
Looking at the logs for V2, it appears there was another service tool connected to the vehicle that was attempting to communicate with the engine at the same time:
2017-06-06 11:21:23.668  P->18EA00F9 DC FE 00
2017-06-06 11:21:23.678  P->18EA00F9 E5 FE 00

These requests were not made by this tool and thus, the testing for validation of this tool is effectively invalid on V2.

**Comment by joekartje** [comment]
Emailed Eric to ask if this can be handled the same way as #16.  That is, either:
1) Address this in the Help file (user checks for rogue modules), or
2) Send requests in a point-to-point manner to HD-OBD Modules, or
3) Assume the Engine (source address zero) MUST respond to all global requests (except for DM11).

**Comment by gumbelmj** [comment]
This has been addressed with #16  and #17.  The request for the response from the engine will be made 3 times if the engine doesn't respond.  The timeout was also increased to 2.5 seconds per request.
