### ISSUE TITLE
Leading Asterisks missing on changed monitor ratios

### ISSUE THREAD

**Issue by joekartje** [Equipment-and-Tool-Institute/iumpr#19]

**Comment by joekartje** [comment]
This should be incorporated with the change to the number comparisons.    
 
M2/D2/YYYY 23:59:59 Monitor Counts from SA 0 Numerator Denominator
  SPN 3048 Ignition Cycle, 1
  SPN 3049 OBD Monitoring Conditions Encountered 1
 \*SPN 5322 NMHC Converting Catalyst System Monitor 0, X\*

**Comment by gumbelmj** [comment]
Added leading asterisks to the Monitors and Ratios Tables when the row has a difference
