### ISSUE TITLE
Correct Time Gap Calculations to reflect only Time Since Code Cleared

### ISSUE THREAD

**Issue by joekartje** [Equipment-and-Tool-Institute/iumpr#20]

**Comment by joekartje** [comment]
It appears that wall clock time (difference) was compared to engine run time.  The difference is to be in engine run time (alone).

**Comment by gumbelmj** [comment]
Neither the wall clock nor the engine hours are being used for this calculation.  It's based solely upon the value returned from the engine to a DM21 request.

**Comment by joekartje** [comment]
This was an issue originally given to me by Eric on Friday (6/16/2017).  It was acknowledged by Eric as an error in yesterday's meeting (6/20/2017).  I am closing it and will notify Eric that it is closed.
