### ISSUE TITLE
Connection Speed missing from log file

### ISSUE THREAD

**Issue by joekartje** [Equipment-and-Tool-Institute/iumpr#22]

**Comment by joekartje** [comment]
Connection speed changes between 2013 and 2016 era engines. If the speed is wrong the adaptor may be listening to the wrong set of pins and not pins C
and D.

**Comment by battjt** [comment]
If we are listening in the wrong pins or at the wrong speed then the adapter is broken and it should be listed as a known bug.  Rp1210 does not exposed speed or pin information to the client.

**Comment by gumbelmj** [comment]
RP1210C has a method "RP1210_Get_Protocol_Connection_Speed" that can be used to get the connection speed.  If the adapter doesn't support this method, an error will be logged in the report

**Comment by joekartje** [comment]
Eric has agreed to the solution that if the adapter selected by the user supports the RP1210C library method to get the connection speed, then Connection Speed will be included in the report.  If it doesn't support this method, "Connection Speed N/A" or "Connection Speed Not Available" will be logged in the report instead of 250 or 500 (Kbps),

**Comment by gumbelmj** [comment]
Using the GET_PROTOCOL_CONNECTION_SPEED command, the is now included in the report as part of the data plate represented as bits-per-second, as reported by the adapter.
