### ISSUE TITLE
Address Claim missing from log file

### ISSUE THREAD

**Issue by joekartje** [Equipment-and-Tool-Institute/iumpr#23]

**Comment by joekartje** [comment]
The address claim request may be executed a second time for the convenience of creating the output and that address claim results used in conjunction with Function A need not be saved in order to be reproduced

**Comment by battjt** [comment]
Address claim is a message handled internally by a rp1210 adapter and not exposed to the client.

**Comment by gumbelmj** [comment]
Testing with the Nexiq adapter, the address claim messages were passed through.  Thus the request for address claim was added to the Data Plate Controller.  In the event no responses are received, it will be noted, but progress will not halt.  Additionally, if no module reports as "Function 0" that will also be noted.
