### ISSUE TITLE
Excess Time Error message after a DM11. This is not possible for a new file.

### ISSUE THREAD

**Issue by joekartje** [Equipment-and-Tool-Institute/iumpr#25]
DM 11 resets the time since code clear. For a data plate report where DM11 is run, there can be no rollover error. The existing value is expected to be erased when DM11 is run.  This error applies to only to reuse of existing files based on the last known value for time since code clear.

**Comment by gumbelmj** [comment]
Was there an error reported after a DM11 reset?

**Comment by joekartje** [comment]
Yes, in V4-D1 (attached)

**Comment by gumbelmj** [comment]
The TSCC in the ReportFileModule wasn't being reset when the faults were cleared.
