### ISSUE TITLE
Remove "supports scaled test results" and freeze frame length from the list of SPNs that support test results.

### ISSUE THREAD

**Issue by joekartje** [Equipment-and-Tool-Institute/iumpr#27]
For example, change...
SPN 5031 - Aftertreatment 1 Outlet NOx Sensor Heater Ratio: Supports Scaled Test Results with data length 0 bytes
...to...
SPN 5031 - Aftertreatment 1 Outlet NOx Sensor Heater Ratio

**Comment by gumbelmj** [comment]
The test results type and data length was removed.  The report only prints the SPNs that support Scaled Tests Results now.
