### ISSUE TITLE
Simplify display of complete and incomplete scaled test results

### ISSUE THREAD

**Issue by joekartje** [Equipment-and-Tool-Institute/iumpr#28]
Suggested display format:
SPN xxxxx FMI xx Result: Test Passed[Failed] Min: xxx Value: xxx Max: xxx [units]. 
Units need not be repeated 3 times. Once after Max xxx will suffice.
This should fit on one line.
(More detail included in Printed_Comments_for_Jun6th_Results.pdf)

**Comment by gumbelmj** [comment]
Condensed the results as suggested.  The number of incomplete tests was being reported, but the number was lost in the timestamp.  The total number of incomplete tests was moved the bottom of the report so it's more apparent.
