### ISSUE TITLE
CVN is a 32-bit little endian CRC

### ISSUE THREAD

**Issue by gumbelmj** [Equipment-and-Tool-Institute/iumpr#35]
CVN is a 32-bit little endian CRC.  00 in a CVN may not be assumed to be padding or a  a string terminator.  Since it is a CRC, it would be best to show all 32 bits.

Below 00 AC FF 33 should appear as 0x33FFAC00

And DE E5 00 00 may be better shown as 0x0000E5DE
Example 1
2017-08-09T10:27:27.344 Global DM19 (Calibration Information) Request 10:27:27.344 18EAFFF9 00 D3 00 (TX) 
10:27:29.844 18D30011 00 00 00 00 4E 58 43 43 43 43 4E 4F 00 00 00 00 00 00 00 00 
DM19 from Cruise Control (17): CAL ID of NXCCCCNO and CVN of 0x0 
10:27:29.844 18D30000 F6 16 DE 8B 41 32 36 32 34 58 58 41 5F 45 32 31 35 33 58 32 A8 73 89 13 4E 4F 78 2D 53 41 45 31 34 61 20 41 54 49 31 00 8C 4B F9 C9 4E 4F 78 2D 53 41 45 31 34 61 20 41 54 4F 31 00 AC FF 33 00 30 32 30 31 30 31 30 30 30 32 00 00 00 00 00 00 D2 BF 0F A9 50 4D 53 31 32 33 34 31 41 31 30 31 00 00 00 00 
DM19 from Engine #1 (0): [ 
 CAL ID of A2624XXA_E2153X2 and CVN of 0x8BDE16F6 
 CAL ID of NOx-SAE14a ATI1 and CVN of 0x138973A8 
 CAL ID of NOx-SAE14a ATO1 and CVN of 0xC9F94B8C 
 CAL ID of 0201010002 and CVN of 0x33FFAC 
 CAL ID of PMS12341A101 and CVN of 0xA90FBFD2 ]

Example 2
2017-08-04T10:54:17.664 Global DM19 (Calibration Information) Request 
10:54:17.664 18EAFFF9 00 D3 00 (TX) 
10:54:20.165 18D30000 25 08 63 66 4D 31 33 31 58 58 42 5F 42 32 38 33 54 45 30 31 
DM19 from Engine #1 (0): CAL ID of M131XXB_B283TE01 and CVN of 0x66630825 10:54:20.165 1CD30055 EB 34 91 AB 31 36 30 32 30 32 4E 4F 30 33 00 00 00 00 00 00 A8 73 89 13 4E 4F 78 2D 53 41 45 31 34 61 20 41 54 49 31 00 8C 4B F9 C9 4E 4F 78 2D 53 41 45 31 34 61 20 41 54 4F 31 00 DE E5 00 00 31 32 44 42 42 32 30 30 30 32 00 00 00 00 00 00 D2 BF 0F A9 50 4D 53 31 32 33 34 31 41 31 30 31 00 00 00 00 
DM19 from Diesel Particulate Filter Controller (85): [ 
 CAL ID of 160202NO03 and CVN of 0xAB9134EB 
 CAL ID of NOx-SAE14a ATI1 and CVN of 0x138973A8 
 CAL ID of NOx-SAE14a ATO1 and CVN of 0xC9F94B8C 
 CAL ID of 12DBB20002 and CVN of 0xE5DE 
 CAL ID of PMS12341A101 and CVN of 0xA90FBFD2 ]

**Comment by gumbelmj** [comment]
All test cases were full 4 bytes.  New cases were added with fewer than 4 bytes and leading zeros were added.

**Comment by joekartje** [comment]
The form submitted for this issue has been posted on the Google Drive:  
https://drive.google.com/open?id=0BzIQ48EeW5tTdFkzSDZ2WFhZMlE
