### ISSUE TITLE
DM5 and DM26 need to also display Supported/Not Supported

### ISSUE THREAD

**Issue by gumbelmj** [Equipment-and-Tool-Institute/iumpr#37]
The linked issue document is: https://drive.google.com/open?id=0BzIQ48EeW5tTWXkzMl90Uld4bE0

Rather than displaying a single status for the monitors from DM5 and DM26, the support bits should have a status displayed in addition to the complete bits.

Thus, in addition to displaying "complete" and "not complete" the report should contain "not supported" and "supported" for DM5 and "not enabled" and "enabled" for DM26

**Comment by gumbelmj** [comment]
As designed, the logic behind both the DM5 and DM26 is common.  By requiring a different status of "supported" and "enabled" requires separating this logic.  Additionally, adding a second field for supported will require adding that column to the Status Tracking UI as well as the overall composite that is reported for DM5's after tracking the Status.  We will require a proposal for how that table shall look with this additional information while also maintaining the column width.

**Comment by joekartje** [comment]
Additional linked issue forms:  https://drive.google.com/open?id=0BzIQ48EeW5tTOWxqNzRVUDl6UUE and 
 https://drive.google.com/open?id=0BzIQ48EeW5tTVG1xZTZLSGlQTVk
