### ISSUE TITLE
Sustain the display of multiple CAL IDs when the UI window is manually resized

### ISSUE THREAD

**Issue by joekartje** [Equipment-and-Tool-Institute/iumpr#44]
The “cals” UI frame is not scaled appropriately in a default window.  If the default window is re-sized, the “cals” block will expand slightly (it should open to this size), or it will collapse into a single line (which is not desired).

Screen shots are included in the submitted issue form which can be found at https://drive.google.com/open?id=0BzIQ48EeW5tTV1hIZENUMkpyWW8

**Comment by gumbelmj** [comment]
If the calibration window is an improper size, adjusting the size of the report text area will change it. @battjt will look to see if there are any reasonable improvements that could be made.
