### ISSUE TITLE
Collect test results request vs. composite results tables

### ISSUE THREAD

**Issue by gumbelmj** [Equipment-and-Tool-Institute/iumpr#52]
The action to “Collect test results” was requested at the end of a test drive.  The test results information was inserted in the end of the test log.  As a result, the composite results tables for DM5 and DM20 were located in the middle of the test log; collecting test results to add to the test log requires a search (scrolling up) for the readiness and IUMPR updates.

---
Presumably, the request is to substitute the Function E formats with the Function C formats for DM20 and DM5.  

The linked issue form is: https://drive.google.com/open?id=0BzIQ48EeW5tTYU9GbFRKNW9CZlU

**Comment by gumbelmj** [comment]
Although this may not take much work it seems to be out of scope.

**Comment by joekartje** [comment]
Substitute Function E formats for Function C formats for DM5 and DM20.  
From Eric:  "The suggestion is to replace the display methods for DM5 and DM20 in Function E with reuse of the existing (as revised in the closed issues) comparative displays in Function C/D for DM5 and DM20.  To succeed, the initial values for DM5 (post DM11) and DM20 obtained in Function B must be visible in Function E (as they are visible in Function C), the method calls in Function E must be replaced with the method calls used in Function C for DM5 and DM20 comparative displays (it may also be necessary to declare the methods used in C to be public methods)."
