### ISSUE TITLE
Generate Data Plate execution sequence - After the new IUMPR log file with an initial Data Plate has been generated and saved, why is it required to re-generate the Data Plate after each repeated opening of the same log file?

### ISSUE THREAD

**Issue by GovindarajKarthik** [Equipment-and-Tool-Institute/iumpr#73]

**Comment by ericthomasswenson** [comment]
The data plate sequence intends that a substitute calibration fails when one to be used in an attempt to create a fraudulent data file.

**Comment by ericthomasswenson** [comment]
When adding to a existing file, confirming that the CAL IDs and CVNs match the original prevents data from being commingled from disparate CAL IDs, and assures the data in the file is coherent. The criteria for other data quality checks is also included in function B. 

These checks were closely negotiated with CARB; I don’t see them changing soon.

**Comment by ericthomasswenson** [comment]
KG agrees with explanation
