### ISSUE TITLE
Task 8 Proposal - Add NOx Binning - GHG Tracking Queries and Tabular Displays to Functions B & E

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/iumpr#84]
Leverage the queries and displays in J1939-84 Part 1 and Part 2 for NOx Binning and GHG Tracking to provide queries and displays For Function B and Function E of the IUMPR tool.
These displays shall precede the test results queries and displays.

**Comment by battjt** [comment]
@ericthomasswenson Please specify a location in the requirements https://github.com/Equipment-and-Tool-Institute/iumpr/blob/c4dc93cc4aac98a400ec823e4b923d6e1d6c5721/docs/IUMPR%20Data%20Collection%20Process.pdf, like "in Function E between step 9 and 10".

**Comment by ericthomasswenson** [comment]
Insert NOX Binning and GHG Tracking Queries

Between 42: and 43: in Function B.

Between 29: and 30: in Function E.

As given in https://github.com/Equipment-and-Tool-Institute/iumpr/blob/c4dc93cc4aac98a400ec823e4b923d6e1d6c5721/docs/IUMPR%20Data%20Collection%20Process.pdf 

Employ the same alternation methods employed in 6.1.26, 6.2.17, and 6.11.13, to define when to query the groups of arrays. 

Employ the same array display methods, as well.

**Comment by ericthomasswenson** [comment]
The 100-Hr active arrays are cleared by DM11.
Their values will document the accumulated values during the trip.
Therefore, detailed difference calculations would be redundant.

**Comment by ericthomasswenson** [comment]
@battjt Please try Function H on a completed demonstration run.
It would be a pity to find out the tabular displays broke the monotonically increasing date time checks, in user’s hands. The are no function H extensions planned for NOx Binning and GHG Tracking.

**Comment by ericthomasswenson** [comment]
In lieu of 

“Employ the same alternation methods employed in 6.1.26, 6.2.17, and 6.11.13, to define when to query the groups of arrays.”

The implementation may query one of the PGs expected for a NOx Binning GHG tracking category to assess support for that category. If the lead PG kis not supported, the rest of the category may be skipped.

Polling using DS queries is expected to be more effective than one global query, for finding support from a distributed OBD system. The OBD ECU supporting the ‘lead PG’ will support the remaining PGs for the category.

**Comment by ericthomasswenson** [comment]
It is reported that the NOx Binning and GHG Tracking displays were not observed in Function B. New issue will be submitted.

**Comment by battjt** [comment]
This was fixed as #89

**Comment by ericthomasswenson** [comment]
IUMPR Complete for Task 8
