### ISSUE TITLE
V1.9.3 Not writing DM19 data to log file

### ISSUE THREAD

**Issue by anthonyhbest** [Equipment-and-Tool-Institute/iumpr#88]
Version 1.9.3 does not appear to consistently writing DM19 response to the log file: 
![image](https://github.com/Equipment-and-Tool-Institute/iumpr/assets/94923793/95593463-de50-4cd7-8880-ff74110f362f)

Which leads to an error when transitioning to Tracking Completion Status or Test Result Collection:
![image](https://github.com/Equipment-and-Tool-Institute/iumpr/assets/94923793/7a3940f0-d952-42ca-b64b-5ea56698461f)

Truck is responding with valid DM19 data:
![image](https://github.com/Equipment-and-Tool-Institute/iumpr/assets/94923793/0d374c2d-8acb-4711-be62-55b75895d5dc)

**Comment by battjt** [comment]
I was unable to reproduce this on my equipment.  I suspect that there was a TP issue.  BAM TP is fragile.  Raw CAN logging was not enabled in IUMPR, so I can't verify it.  In the next release RAW CAN logging will be enabled, so we can retest.

**Comment by battjt** [comment]
@anthonyhbest  The new release (1.9.4) correctly logs all of the CAN traffic into a vector compatible .ASC file in %TEMP%. .  I suspect that we have a J1939-21 transport protocol timing problem.  Could you rerun your test and send this file to me? 
![image](https://github.com/Equipment-and-Tool-Institute/iumpr/assets/1972001/97805c10-a34c-4942-8ed3-f063118fcf70)

**Comment by anthonyhbest** [comment]
@battjt I reran the test this morning but the tool is now working and logging correctly.  I will try it out on a few other trucks over the next week and see if we can replicate the original issue.

**Comment by ericthomasswenson** [comment]
IUMPR Complete for Task8
