### ISSUE TITLE
No NOx Binning or GHG Tracking tables

### ISSUE THREAD

**Issue by anthonyhbest** [Equipment-and-Tool-Institute/iumpr#89]
Tested V1.9.3 and did not see any NOx Binning or GHG tracking tables in either Function B or E.

**Comment by battjt** [comment]
The tests for if the DM24 contains the key SPNs for the tables was using the SPNs of the DM24, not the SPNs listed as supported in the DM24.

**Comment by anthonyhbest** [comment]
Tested v1.9.4 and NOx Binning and GHG Tracking appear to be working correctly now.

**Comment by ericthomasswenson** [comment]
IUMPR complete for Task 8
