### ISSUE TITLE
CAL ID displayed incorrectly 

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/iumpr#90]
Similar to #88 .. Examples to be provided by KG.

**Comment by GovindarajKarthik** [comment]
Version 1.9.4, does not write the DM19 response from all the ECUs. Resulting in an error when tool compares Report Calibrations with Vehicle Calibrations.
![DM19 Issue V1 9 4](https://github.com/Equipment-and-Tool-Institute/iumpr/assets/40402282/7be02e53-3612-4101-9352-67c0bf24392b)

**Comment by battjt** [comment]
This isn't the first report of this problem, so I'm not arguing that there isn't a problem, but I need more to understand this issue.  Your report only includes one response to a global request for DM19 and the response appears to be correctly decoded. Our testing is working with multiple modules, one has multiple DM19 entries and the other is a single.

Were there multiple responses?  If the tool is missing responses, then I need a CAN log to understand why. (find the latest .asc file in "%TEMP%")  We may need to be more lenient of the TP timeouts.  Maybe the tool failed to log TP errors to the report.

What adapter are you using?  High latency adapters will have more timing issues resulting in more TP failures.

**Comment by GovindarajKarthik** [comment]
The expectation was to receive DM19 responses from multiple modules but there was only one response to DM19. I had reported a similar issue last year on v1.3 and you fixed it in v1.5. ( Details in the attachment)

The adapter used was for testing v1.9.4 is nexiq usb 2. It has been a few weeks since the tool was tested, I am unable to find the requested CAN log in temp folder now. Please let me know If needed, I can try to connect to the tool again and see if it populates the CAN log/.asc file that you requested in the below email.

Regards,
Karthik Govindaraj

**Comment by battjt** [comment]
Your github "comment via email" doesn't include an attachment.  That may be a github issue.

Yes, I need a .asc file to diagnose this.  It is probably a TP timing issue.  IUMPR 1.5.0 used the adapter TP.  Starting with 1.9.0 IUMPR implements TP to improve error reporting of bad TP.

**Comment by ericthomasswenson** [comment]
I’ve seen emails with confirming complaints.

**Comment by battjt** [comment]
Further testing does not support this.
~~The J1939 routines copied from the J1939-84 project use 750 ms as the response timeout.  It had been 2500 ms.  Examples provided took 756.225 ms (using a 50 ms interpacket delay).  I recommend switching the timeout back to 2500 ms.~~

**Comment by battjt** [comment]
The multiple DM19 responses are on the screen report, but not in the file.  I am able to reproduce this reliably now.

**Comment by battjt** [comment]
The new J1939 stack was returning responses in the order first response, not the order the the final packet.  The timestamps were then being added to the file out of order, causing an error condition in the logs.  Sorting the responses by final packet timestamp allows them to be added to the file in the correct order avoiding the error.

**Comment by ericthomasswenson** [comment]
Still waiting for confirmation of fix.

**Comment by GovindarajKarthik** [comment]
This issue is still not resolved in version 1.9.5.

Karthik Govindaraj

**Comment by ericthomasswenson** [comment]
1.9.5 appears to have corrected this issue.
