### ISSUE TITLE
DM5 Responses Omitted from Data Plate Report

### ISSUE THREAD

**Issue by ericthomasswenson** [Equipment-and-Tool-Institute/iumpr#98]
DM5 Responses Omitted from Data Plate Report

2024-03-06T06:31:03.6699 IUMPR Data Collection Tool Data Plate Report 

2024-03-06T06:31:06.7319 Global DM5 Request
06:31:06.7319 18EAFFF9 [3] CE FE 00 (TX)
06:31:06.7447 18FECE00 [8] 00 00 14 27 E0 0E E0 0E
 
06:31:06.7794 18FECE17 [8] 00 00 05 00 00 00 00 00
 // Omitted below 
Engine #1 (0) reported as an HD-OBD Module.
Management Computer #1 (39) reported as an HD-OBD Module.
 // Omitted above 
Exhaust Emission Controller (61) reported as an HD-OBD Module. // Omitted above 

Report file emailed 3/7/2024

**Comment by ericthomasswenson** [comment]
Also observed at

2024-03-07T12:26:27.2968 Global DM5 Request
12:26:27.2968 18EAFFF9 [3] CE FE 00 (TX)
12:26:27.3145 18FECE00 [8] 00 00 14 07 E0 0E 20 04
12:26:27.3499 18FECE17 [8] 00 00 05 00 00 00 00 00
Engine #1 (0) reported as an HD-OBD Module.
Management Computer #1 (39) reported as an HD-OBD Module.
Exhaust Emission Controller (61) reported as an HD-OBD Module.

in
2024-03-07T12:26:24.2921 IUMPR Data Collection Tool Data Collection Log

**Comment by ericthomasswenson** [comment]
Here all responses are displayed:

2024-03-06T06:31:08.4885 Clearing Diagnostic Trouble Codes
06:31:08.4885 Global DM11 Request
06:31:08.4896 18EAFFF9 [3] D3 FE 00 (TX)
Diagnostic Trouble Codes were successfully cleared.

2024-03-06T06:31:09.9925 Global DM5 Request
06:31:09.9925 18EAFFF9 [3] CE FE 00 (TX)
06:31:10.0038 18FECE00 [8] [00 00 14 27](tel:00 00 14 27) E0 0E E0 0E
DM5 from Engine #1 (0): OBD Compliance: HD OBD (20), Active Codes: 0, Previously Active Codes: 0
Continuously Monitored System Support/Status:
    Comprehensive component        supported,     complete
    Fuel System                    supported, not complete
    Misfire                        supported,     complete
Non-continuously Monitored System Support/Status:
    A/C system refrigerant     not supported,     complete
    Boost pressure control sys     supported, not complete
    Catalyst                   not supported,     complete
    Cold start aid system      not supported,     complete
    Diesel Particulate Filter      supported, not complete
    EGR/VVT system                 supported, not complete
    Evaporative system         not supported,     complete
    Exhaust Gas Sensor             supported, not complete
    Exhaust Gas Sensor heater      supported, not complete
    Heated catalyst            not supported,     complete
    NMHC converting catalyst   not supported,     complete
    NOx catalyst/adsorber          supported, not complete
    Secondary air system       not supported,     complete
06:31:10.0189 18FECE17 [8] [00 00 05 00 00 00 00](tel:00 00 05 00 00 00 00) 00
DM5 from Instrument Cluster #1 (23): OBD Compliance: Not intended to meet OBD II requirements (5), Active Codes: 0, Previously Active Codes: 0
Continuously Monitored System Support/Status:
    Comprehensive component    not supported,     complete
    Fuel System                not supported,     complete
    Misfire                    not supported,     complete
Non-continuously Monitored System Support/Status:
    A/C system refrigerant     not supported,     complete
    Boost pressure control sys not supported,     complete
    Catalyst                   not supported,     complete
    Cold start aid system      not supported,     complete
    Diesel Particulate Filter  not supported,     complete
    EGR/VVT system             not supported,     complete
    Evaporative system         not supported,     complete
    Exhaust Gas Sensor         not supported,     complete
    Exhaust Gas Sensor heater  not supported,     complete
    Heated catalyst            not supported,     complete
    NMHC converting catalyst   not supported,     complete
    NOx catalyst/adsorber      not supported,     complete
    Secondary air system       not supported,     complete
DM5 from Passenger-Operator Climate Control #1 (25): OBD Compliance: Not intended to meet OBD II requirements (5), Active Codes: 0, Previously Active Codes: 0
Continuously Monitored System Support/Status:
    Comprehensive component    not supported,     complete
    Fuel System                not supported,     complete
    Misfire                    not supported,     complete
Non-continuously Monitored System Support/Status:
    A/C system refrigerant     not supported,     complete
    Boost pressure control sys not supported,     complete
    Catalyst                   not supported,     complete
    Cold start aid system      not supported,     complete
    Diesel Particulate Filter  not supported,     complete
    EGR/VVT system             not supported,     complete
    Evaporative system         not supported,     complete
    Exhaust Gas Sensor         not supported,     complete
    Exhaust Gas Sensor heater  not supported,     complete
    Heated catalyst            not supported,     complete
    NMHC converting catalyst   not supported,     complete
    NOx catalyst/adsorber      not supported,     complete
    Secondary air system       not supported,     complete
DM5 from Management Computer #1 (39): OBD Compliance: HD OBD (20), Active Codes: 0, Previously Active Codes: 0
Continuously Monitored System Support/Status:
    Comprehensive component        supported,     complete
    Fuel System                not supported,     complete
    Misfire                    not supported,     complete
Non-continuously Monitored System Support/Status:
    A/C system refrigerant     not supported,     complete
    Boost pressure control sys not supported,     complete
    Catalyst                   not supported,     complete
    Cold start aid system      not supported,     complete
    Diesel Particulate Filter  not supported,     complete
    EGR/VVT system             not supported,     complete
    Evaporative system         not supported,     complete
    Exhaust Gas Sensor         not supported,     complete
    Exhaust Gas Sensor heater  not supported,     complete
    Heated catalyst            not supported,     complete
    NMHC converting catalyst   not supported,     complete
    NOx catalyst/adsorber      not supported,     complete
    Secondary air system       not supported,     complete
DM5 from Exhaust Emission Controller (61): OBD Compliance: HD OBD (20), Active Codes: 0, Previously Active Codes: 0
Continuously Monitored System Support/Status:
    Comprehensive component        supported,     complete
    Fuel System                not supported,     complete
    Misfire                    not supported,     complete
Non-continuously Monitored System Support/Status:
    A/C system refrigerant     not supported,     complete
    Boost pressure control sys not supported,     complete
    Catalyst                   not supported,     complete
    Cold start aid system      not supported,     complete
    Diesel Particulate Filter  not supported,     complete
    EGR/VVT system             not supported,     complete
    Evaporative system         not supported,     complete
    Exhaust Gas Sensor         not supported,     complete
    Exhaust Gas Sensor heater  not supported,     complete
    Heated catalyst            not supported,     complete
    NMHC converting catalyst   not supported,     complete
    NOx catalyst/adsorber      not supported,     complete
    Secondary air system       not supported,     complete

Vehicle Composite of DM5:
    A/C system refrigerant     not supported,     complete
    Boost pressure control sys     supported, not complete
    Catalyst                   not supported,     complete
    Cold start aid system      not supported,     complete
    Comprehensive component        supported,     complete
    Diesel Particulate Filter      supported, not complete
    EGR/VVT system                 supported, not complete
    Evaporative system         not supported,     complete
    Exhaust Gas Sensor             supported, not complete
    Exhaust Gas Sensor heater      supported, not complete
    Fuel System                    supported, not complete
    Heated catalyst            not supported,     complete
    Misfire                        supported,     complete
    NMHC converting catalyst   not supported,     complete
    NOx catalyst/adsorber          supported, not complete
    Secondary air system       not supported,     complete

**Comment by ericthomasswenson** [comment]
Confirm release schedule.

**Comment by karysg** [comment]
Issue resolved by commit 6af54aed, merged in pull request #106

**Comment by ericthomasswenson** [comment]
Looks much better now
